/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ezbakeBaseTypes_ttypes = require('./ezbakeBaseTypes_types')
var ezmetrics_ttypes = require('./ezmetrics_types')


var ttypes = require('./ezbakeBaseService_types');
//HELPER FUNCTIONS AND STRUCTURES

ezbake.base.thrift.EzBakeBaseService_ping_args = function(args) {
};
ezbake.base.thrift.EzBakeBaseService_ping_args.prototype = {};
ezbake.base.thrift.EzBakeBaseService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('EzBakeBaseService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ezbake.base.thrift.EzBakeBaseService_ping_result.prototype = {};
ezbake.base.thrift.EzBakeBaseService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('EzBakeBaseService_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args = function(args) {
};
ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args.prototype = {};
ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args.prototype.write = function(output) {
  output.writeStructBegin('EzBakeBaseService_getMetricRegistryThrift_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result.prototype = {};
ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ezmetrics_ttypes.MetricRegistryThrift();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result.prototype.write = function(output) {
  output.writeStructBegin('EzBakeBaseService_getMetricRegistryThrift_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ezbake.base.thrift.EzBakeBaseServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
ezbake.base.thrift.EzBakeBaseServiceClient.prototype = {};
ezbake.base.thrift.EzBakeBaseServiceClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

ezbake.base.thrift.EzBakeBaseServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new ezbake.base.thrift.EzBakeBaseService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ezbake.base.thrift.EzBakeBaseServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ezbake.base.thrift.EzBakeBaseService_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
ezbake.base.thrift.EzBakeBaseServiceClient.prototype.getMetricRegistryThrift = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getMetricRegistryThrift();
};

ezbake.base.thrift.EzBakeBaseServiceClient.prototype.send_getMetricRegistryThrift = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getMetricRegistryThrift', Thrift.MessageType.CALL, this.seqid);
  var args = new ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ezbake.base.thrift.EzBakeBaseServiceClient.prototype.recv_getMetricRegistryThrift = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getMetricRegistryThrift failed: unknown result');
};
ezbake.base.thrift.EzBakeBaseServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ezbake.base.thrift.EzBakeBaseServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ezbake.base.thrift.EzBakeBaseServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new ezbake.base.thrift.EzBakeBaseService_ping_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ping(function (err, result) {
    var result = new ezbake.base.thrift.EzBakeBaseService_ping_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

ezbake.base.thrift.EzBakeBaseServiceProcessor.prototype.process_getMetricRegistryThrift = function(seqid, input, output) {
  var args = new ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.getMetricRegistryThrift(function (err, result) {
    var result = new ezbake.base.thrift.EzBakeBaseService_getMetricRegistryThrift_result((err != null ? err : {success: result}));
    output.writeMessageBegin("getMetricRegistryThrift", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

